export const icons = {
    more: "eva:more-vertical-fill",
    riMore: "ri:more-fill",
    plus: "eva:plus-fill",
    tip: "mingcute:warning-line",
    edit: "material-symbols:edit",
    delete: "eva:trash-2-outline",
    files: "material-symbols:file-copy",
    folders: "ic:round-perm-media",
    report: "system-uicons:document-list",
    enable: "material-symbols:closed-caption",
    disable: "material-symbols:closed-caption-disabled-outline",
    check: "eva:checkmark-circle-2-fill",
    unCheck: "ph:x-circle-fill",
    copy: "tabler:copy",
    download: "material-symbols:sim-card-download-rounded",
    id: "mdi:id-card-outline",
    closingTag: "material-symbols:code-off",
    refresh: "charm:refresh",
    stop: "mdi:stop-circle",
    doublePlay: "tabler:player-track-next-filled",
    reload: "oi:reload",
    like: "fontisto:like",
    block: "fluent:presence-blocked-20-regular",
    upload: "eva:cloud-upload-fill",
    calendar: "eva:calendar-fill",
    options: "eva:options-2-outline",
    form: "clarity:form-line",
    package: "mdi:package-outline",
    message: "uil:comment-message",
    list: "fluent:list-24-filled",
    users: "ph:users-three-bold",
    user: "mdi:user-circle",
    electric: "material-symbols:electric-bolt",
    networkChecked: "material-symbols:network-check",
    // directions
    arrow: "eva:arrow-ios-forward-fill",
    moveY: "pepicons-pop:move-y",
    next: "mdi:navigate-next",
    doubleNext: "material-symbols:keyboard-double-arrow-right",
    back: "mdi:navigate-before",
    doubleBack: "material-symbols:keyboard-double-arrow-left",
    update: "ic:twotone-update",
    clean: "healthicons:cleaning",
    disk: "clarity:hard-disk-solid-alerted",
    top: "fluent-emoji-high-contrast:top-arrow",
    sortAsc: "ph:sort-ascending-bold",
    removeUsers: "mdi:user-multiple-remove-outline",
    record: "material-symbols:record-voice-over",
    archive: "material-symbols:archive-outline",
    search: "eva:search-fill",
    questionMark: "mdi:question-mark-circle-outline",
    circleSelect: "ic:outline-radio-button-checked",
    status: "ic:twotone-circle",
    speed:"icon-park-solid:speed-one",



    // 
    price: "arcticons:priceconverter",
    cart: "ic:baseline-production-quantity-limits",
    table: "majesticons:table-line",
    invoice: "ic:baseline-receipt-long",
    van: "mdi:truck-check",
    qrCode: "ri:qr-scan-line",
    box: "mingcute:empty-box-line",

};